# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dungeon Architects
subtitle: Network
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Up your game with some of the best resources from
  the community of tabletop roleplaying game masters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dungeonarchitects.network" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag

# Blog Settings
permalink: /articles/:slug

collections:
  resources:
    permalink: /resources/:path

defaults:
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
